# This is the workflow to lint the source code
name: Test Code

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: 'ğŸ› ï¸ Test Code'
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright # Provide browser instances for test runners

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'âš™ï¸ Use Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'

      - name: 'â›“ï¸ Install dependencies'
        env:
          HUSKY: 0
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: 'â›“ï¸ Install puppeteer' # Needed to provide a browser to webhint
        run: npm i -D puppeteer

      # In this repository, building is much faster than the upload/download of the artifact
      - name: 'ğŸ› ï¸ Build'
        run: npm run build --if-present

      # - name: 'ğŸ“ Download build output'
      #   uses: actions/download-artifact@v3
      #   continue-on-error: true # There won't be an artifact in workflow without build job
      #   with:
      #     name: build
      #     path: dist

      - name: 'ğŸ§« Run tests'
        continue-on-error: true # temporary fix for https://github.com/webhintio/hint/issues/5432
        run: npm run test --if-present
